set DEFINE off
set sqlbl on
ALTER SESSION SET sort_area_size=5000000
;

CREATE INDEX XL_COND_ERA_CONCEPT_ID ON CONDITION_ERA (CONDITION_CONCEPT_ID ASC)
NOLOGGING
;
CREATE INDEX XN_COND_ERA_PERSON_ID ON CONDITION_ERA (PERSON_ID ASC)
NOLOGGING
;
CREATE INDEX XN_COND_ERA_START_DATE ON CONDITION_ERA (CONDITION_ERA_START_DATE ASC)
NOLOGGING
;


CREATE INDEX XL_COND_OCC_CONCEPT_ID ON CONDITION_OCCURRENCE (CONDITION_CONCEPT_ID ASC)
NOLOGGING
;
CREATE INDEX XN_COND_OCCUR_PERSON_ID ON CONDITION_OCCURRENCE (PERSON_ID ASC)
NOLOGGING
;
CREATE INDEX XN_COND_OCCUR_START_DATE ON CONDITION_OCCURRENCE (CONDITION_START_DATE ASC)
NOLOGGING
;


CREATE INDEX XL_DRUG_ERA_CONCEPT_ID ON DRUG_ERA (DRUG_CONCEPT_ID ASC)
NOLOGGING
;
CREATE INDEX XN_DRUG_ERA_PERSON_ID ON DRUG_ERA (PERSON_ID ASC)
NOLOGGING
;
CREATE INDEX XN_DRUG_ERA_START_DATE ON DRUG_ERA (DRUG_ERA_START_DATE ASC)
NOLOGGING
;

CREATE INDEX XL_DRUG_EXP_CONCEPT_ID ON DRUG_EXPOSURE (DRUG_CONCEPT_ID ASC)
NOLOGGING
;
CREATE INDEX XN_DRUG_EXP_PERSON_ID ON DRUG_EXPOSURE (PERSON_ID ASC)
NOLOGGING
;
CREATE INDEX XN_DRUG_EXP_START_DATE ON DRUG_EXPOSURE (DRUG_EXPOSURE_START_DATE ASC)
NOLOGGING
;


CREATE INDEX XN_OBS_PERIOD_PERSON_ID ON OBSERVATION_PERIOD (PERSON_ID ASC)
NOLOGGING
;
CREATE INDEX XN_OBS_PERIOD_START_DATE ON OBSERVATION_PERIOD (OBSERVATION_PERIOD_START_DATE ASC)
NOLOGGING
;


CREATE UNIQUE INDEX XPK_PERSON_PERSON_ID ON PERSON (PERSON_ID ASC)
NOLOGGING
;

CREATE INDEX XL_PROC_OCCUR_CONCEPT_ID ON PROCEDURE_OCCURRENCE (PROCEDURE_CONCEPT_ID ASC)
NOLOGGING
;
CREATE INDEX XN_PROC_OCCUR_PERSON_ID ON PROCEDURE_OCCURRENCE (PERSON_ID ASC)
NOLOGGING
;
CREATE INDEX XN_PROC_OCCUR_START_DATE ON PROCEDURE_OCCURRENCE (PROCEDURE_DATE ASC)
NOLOGGING
;

CREATE INDEX XL_VISIT_OCCUR_PERSON_ID ON VISIT_OCCURRENCE (PERSON_ID ASC)
NOLOGGING
;
CREATE INDEX XN_VISIT_CONCEPT_ID ON VISIT_OCCURRENCE (VISIT_CONCEPT_ID ASC)
NOLOGGING
;
CREATE INDEX XN_VISIT_OCCUR_START_DATE ON VISIT_OCCURRENCE (VISIT_START_DATE ASC)
NOLOGGING
;

SET HEADING OFF
SELECT '*** EXTRACT EXECUTE COMPLETED ***' FROM DUAL
;

EXIT
